### ISSUE TITLE
[Feature Request] Add type hints

### ISSUE THREAD

**Issue by SauravMaheshkar** [LiorZ/Kinetix#3]
Hey @LiorZ, I found this repository via the `#protein-universe` channel on the OpenBioML discord and wanted to use the library but I can't figure out the data types for some of the core classes such as `ReactionParameters` and `Enzyme`, it'd be nice if you could add type hints for more clarity.

**Comment by LiorZ** [comment]
Thanks a lot for this request. I will include typw hinting in the next release

**Comment by LiorZ** [comment]
Implemented in commit f312fb63073d2430269ec0437a13922ca3a4e034
